### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by capcionista** [viddo/atom-global-shortcuts#1]
Instead of setting a shortcut, the ENTER key is displayed as pressed as if I wanted to make it part of shortcut. (Windows 10)
No shortcut (neither with or without "enter"-key is added)

I would be really grateful if you could make the package work on windows.

Thank you :+1:

**Comment by viddo** [comment]
I missed this issue report back in June (I had a bunch of repos unwatched…). Sorry about that. 😞 

I've just released a fix (v0.2.1, see #3 ). The error you describe sounds a lot like a fault in the keystrokes-view that I also fixed in this release, that was due to some changes in Atom's keymaps API since this package was originally implemented in 2015. 

I don't use Windows (or this package anymore really) so have a hard time validating this, but there's nothing special in this package that is OS specific so it _should_ work on any platform really. I'll close this issue since I believe the last release fixed it, feel free to reopen if I'm wrong.
